### ISSUE TITLE
Ensure labels are of a consistent length

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk#162] opened 2021-08-23 15:09 UTC
A lot of the variables are too long, and ideally could be multi-purpose labels to expose to other tools, e.g. PolicyEngine. Shortening them all to within 3-4 words could make this possible.

**Comment by MaxGhenis** [comment] 2021-12-28 21:55
Duplicate of #157

**Closed by MaxGhenis** 2021-12-28 21:55 UTC
